Fixed shared library not found error
ezsystems/docker-php pull request #24
Opened 2017-06-12 14:03 UTC by kmadejski

### Description

In Docker images for PHP 5.5 and PHP 5.6 `libmemcached-dev` was removed after installation what caused error `PHP Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-xxx/memcached.so`.

The same issue exists in PHP 7.1 Docker image which is currently in Docker Hub. 
After image rebuild, the issue no longer exists. Image available in Docker Hub should be rebuilt and committed again.

2017-06-12 14:49 UTC, andrerom requested changes
Not where it is supposed to have packages.

mgiht want to try to backport this instead: https://github.com/ezsystems/docker-php/commit/66929a3fd7e79a5f857de471612ba8eefd91955f

2017-06-13 09:01 UTC, kmadejski commented
@andrerom Thank you for review.

The whole configuration for PHP 7.0 and 7.1 is perfect, just need to rebuild the image. 
I did rebuild locally and both images work well.

I've tried different ways to configure memcached for PHP 5.5 and 5.6:

a)
``
&& echo no | pecl install memcached \
&& docker-php-ext-enable memcached \
``
causes:
``
pecl/memcached requires PHP (version >= 7.0.0), installed version is 5.5.38
No valid packages found
install failed
``

b)
``
 && pecl install memcached-2.2.0 \
    && echo "extension=memcached.so" > ${PHP_INI_DIR}/conf.d/memcached.ini \
``
without:
``
&& doNotUninstall=" \
        libmemcached11 \
        libmemcachedutil2 \
    " \
``
causes:
``
PHP Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-xxx/memcached.so
``

in both cases memcached not working.

2017-06-13 09:29 UTC, andrerom commented
So you definitely need ´pecl install memcached-2.2.0´ here as pecl is unfortunately not smart enough to pick latests that is valid for given php version. So my suggestion was not to get rid of that, but to align everything else.

In both cases basically:
```diff
diff --git a/php/Dockerfile-5.6 b/php/Dockerfile-5.6
index 8790b20..fd60ff6 100644
--- a/php/Dockerfile-5.6
+++ b/php/Dockerfile-5.6
@@ -23,7 +23,7 @@ RUN apt-get update -q -y \
         libpng12-0 \
         libicu52 \
         libxslt1.1 \
-        libmemcached11 \
+        libmemcachedutil2 \
 # git & unzip needed for composer, unless we document to use dev image for composer install
 # unzip needed due to https://github.com/composer/composer/issues/4471
         unzip \
@@ -61,11 +61,11 @@ RUN set -xe \
     \
 # Install redis
     && pecl install redis \
-    && echo "extension=redis.so" > ${PHP_INI_DIR}/conf.d/redis.ini \
+    && docker-php-ext-enable redis \
     \
 # Install memcached (as we are on Debian 8 we have libmemcached 1.0.18 which is recommended)
-    && pecl install memcached-2.2.0 \
-    && echo "extension=memcached.so" > ${PHP_INI_DIR}/conf.d/memcached.ini \
+    && echo no | pecl install memcached-2.2.0 \
+    && docker-php-ext-enable memcached \
     \
 # Delete source & builds deps so it does not hang around in layers taking up space
     && docker-php-source delete \
```

2017-06-13 09:48 UTC, kmadejski commented
@andrerom Fixed. Thank you for your great advice. 
Both 5.5 and 5.6 tested and work well.

2017-06-13 09:50 UTC, andrerom approved these changes
+1, awaiting what travis says, but I expect it to only fail on 7.0 given it pulls in ezplatform-alpha2 which has a lock file generated on php-7.1

2017-06-13 10:21 UTC, andrerom commented
@kmadejski To try to get tests passing, so builds will happen on merge, could you apply the following?

```diff
diff --git a/bin/.travis/test.sh b/bin/.travis/test.sh
index a21a98d..d16b310 100755
--- a/bin/.travis/test.sh
+++ b/bin/.travis/test.sh
@@ -28,7 +28,8 @@ if [ "$FORMAT_VERSION" = "" ]; then
 fi
 
 if [ "$EZ_VERSION" = "" ]; then
-    EZ_VERSION="@alpha"
+    # pull in latests stable by default
+    EZ_VERSION=""
 fi
 
 
diff --git a/bin/.travis/testSymfonyRequirements.php b/bin/.travis/testSymfonyRequirements.php
index c2a0289..e2279b2 100644
--- a/bin/.travis/testSymfonyRequirements.php
+++ b/bin/.travis/testSymfonyRequirements.php
@@ -2,7 +2,12 @@
 
 echo ("Running testSymfonyRequirements.php...\n");
 
-require_once dirname(__FILE__) . '/app/SymfonyRequirements.php';
+// Symfony 2 or 3 structure?
+if (file_exists(dirname(__FILE__) . '/app/SymfonyRequirements.php')) {
+    require_once dirname(__FILE__) . '/app/SymfonyRequirements.php';
+} else {
+    require_once dirname(__FILE__) . '/var/SymfonyRequirements.php';
+}
 
 $symfonyRequirements = new SymfonyRequirements();
```

2017-06-13 11:07 UTC, andrerom commented
Thanks @kmadejski, merging 👍

2017-06-13 11:07 UTC, merged