[WIP] Changed Node version to 12 for v2 version of images
ezsystems/docker-php pull request #49
Opened 2020-05-26 13:25 UTC by mnocon

As suggested in discussion here: https://github.com/ezsystems/developer-documentation/pull/1012 we should try running tests on Travis using Node 12.

It has been verified manually that this version works correctly with Platform 3.0: https://jira.ez.no/browse/EZP-31553

I'd like to keep both versions of Node available (10 and 12), so that we can use Node 10 to run tests on v2 and Node 12 to run tests on v3.

If I understand correctly this can be achieved by bumping the `FORMAT_VERSION` variable:
image `ezsystems/php:7.3-v1-node` will contain Node 10 (as it used to) and `ezsystems/php:7.3-v2-node` will contain Node 12.

2020-05-26 14:52 UTC, mnocon commented
I don't think there's anything I can do about Travis here (looks like we should release a new version of 1.13?)

2020-05-27 15:58 UTC, andrerom commented
Yes, it's due to https://github.com/ezsystems/docker-php/issues/47

But testing might fail on 1.x with this node version?
Cause if so that leads us into a chicken and egg situation until we can drop 1.x completely and the PHP versions we use for it, which we need for as long as it's within service life and hence needs occasional QA testing on it still..

2020-05-28 06:15 UTC, bogusez approved these changes

2020-05-28 06:52 UTC, vidarl commented
> But testing might fail on 1.x with this node version?
Then it is time to bump to v2 for these php images, let 1.x use v1 and change 2.x and 3.x to use v2 IMO

2020-05-28 06:58 UTC, vidarl requested changes
So if we agree to building both v1 and v2, I think we need create a "v1" branch before merging this?

2020-05-28 08:28 UTC, andrerom commented
OK, if we first do a v2 anything else anyone has been eager to change / upgrade?

2020-05-28 08:30 UTC, andrerom commented
Cause if it's only node we could consider adding several node images, changing the one we have to `Dockerfile-node10` and add one for latests LTS we can use already as well (12 or 14).

2020-05-28 08:34 UTC, mnocon commented
I thought about it, but didn't know how to approach the `dev` variant then (right now it's based on the `node` one). Keeping the Node10 image for eZ Platform 2.5 we would need to have `php-X-node10-dev` and `php-X-node12-dev` for Platform 3.0, which seems like an overkill or?

2020-05-28 11:16 UTC, andrerom commented
True, ok strike that

2020-06-03 12:48 UTC, mnocon commented
If we agree to building both v1 and v2 could you (@andrerom , @vidarl ) create a v1 branch?
Or should I try it? (I think I have an idea how to do it, but don't want to overstep here).

2020-06-04 10:11 UTC, andrerom commented
Feel free @mnocon, in short create new v1 branch based on master, and then adapt this PR to make master v2

2020-07-31 10:04 UTC, closed without merging